name: Daily News Bot


on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    environment: BotEnv   # <--- This ties it to your environment
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot script
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CHANNEL_ID_LIVE: ${{ secrets.CHANNEL_ID_LIVE }}
          CHANNEL_ID_TEST: ${{ secrets.CHANNEL_ID_TEST }}
        run: python NewsQuery.py
