name: Daily Discord Bot

on:
  schedule:
    - cron: "0 9 * * *"   # 9:00 UTC every day
  workflow_dispatch:       # lets you trigger manually from the Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python NewsQuery.py
